sudo: required
dist: cosmic
language: python
python:
  - "3.6"
  # # PyPy versions
  # - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  # - pip install -r requirements.txt
  - pip install numpy
  - pip install pytest
  - pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.4.0-cp36-cp36m-manylinux2010_x86_64.whl
# command to run tests
script: python -m pytest